WITH END_DT AS
(
SELECT DATEADD(DAY,-1,[FIRST_MONTH_DT]) END_DT FROM [Modeled_UWHealth].[DIM_DATE]
WHERE ACTUAL_DT = (SELECT DATEADD(DAY,-15,CAST(GETDATE() AS DATE)))
)
,

PRIN_BUILD AS 

(SELECT *, RANK() OVER (PARTITION BY [STRATA_ENCOUNTER_REC_NBR] ORDER BY CHARGE_AMOUNT DESC) RANK1
FROM (
SELECT [STRATA_ENCOUNTER_REC_NBR], [GL_BUILDING_ID], SUM(CHARGE_AMOUNT) CHARGE_AMOUNT
FROM [Mart_UWHealth].[STRATA_COST_CHARGE_ACTIVITY_HB]
GROUP BY [STRATA_ENCOUNTER_REC_NBR], [GL_BUILDING_ID]
HAVING SUM(CHARGE_AMOUNT) > 0
) A)
,
MED_IP AS (
SELECT 
A.[STRATA_ENCOUNTER_REC_NBR], --18,824 IPs
'Medical Inpatients' POPL, 
CASE WHEN [PRIN_GL_BUILDING_ID] IS NULL THEN B.GL_BUILDING_ID ELSE PRIN_GL_BUILDING_ID END AS PRIN_GL_BUILDING_ID
  FROM [Mart_UWHealth].[STRATA_COST_ACCOUNT_HB] A
  INNER JOIN  [Mart_UWHealth].[REF_ALL_MSDRG_CLINGRP]  C ON A.MSDRG_CODE = C.[MSDRG_ALPHA]
  LEFT JOIN PRIN_BUILD B  ON A.[STRATA_ENCOUNTER_REC_NBR] = B.[STRATA_ENCOUNTER_REC_NBR]  AND B.RANK1 = 1

  WHERE C.[HCFA_MEDSURG] = 'Medical'  --Medical MSDRGs
AND [INOUT_IND] = 'IP'
AND DISCHARGE_DT >= '3/1/2024'
AND A.DISCHARGE_DT <= (SELECT END_DT FROM END_DT)
AND A.CHARGE_AMOUNT > 0
AND SERVICE_AREA_ID = '10000'
)
,
ED_NO_IP AS
(SELECT A.[STRATA_ENCOUNTER_REC_NBR],
'ED Not Admitted' POPL,  --84,182
CASE 
WHEN (B.[PRIN_GL_BUILDING_ID] IS NULL OR B.[PRIN_GL_BUILDING_ID] = '1080') AND B.[PATIENT_AGE_DOS] < 18 THEN '1081'
WHEN B.[PRIN_GL_BUILDING_ID] IS NULL THEN C.GL_BUILDING_ID ELSE B.PRIN_GL_BUILDING_ID END AS PRIN_GL_BUILDING_ID,
SUM(A.CHARGE_AMOUNT) CHARGE_AMOUNT
FROM
[Mart_UWHealth].[STRATA_COST_CHARGE_ACTIVITY_HB] A
INNER JOIN [Mart_UWHealth].[STRATA_COST_ACCOUNT_HB] B ON A.[STRATA_ENCOUNTER_REC_NBR] = B.[STRATA_ENCOUNTER_REC_NBR]
LEFT JOIN PRIN_BUILD C  ON A.[STRATA_ENCOUNTER_REC_NBR] = C.[STRATA_ENCOUNTER_REC_NBR]  AND C.RANK1 = 1
WHERE 1=1
AND A.[CHARGE_DEPARTMENT_ID] IN ('22122','37001') --UWH ED and EMH ED DEPs
AND B.[PATIENT_TYPE_CD] <> '3' --	3 - Observation
AND B.DISCHARGE_DT >= '3/1/2024'
AND B.DISCHARGE_DT <= (SELECT END_DT FROM END_DT)
AND B.[INOUT_IND] = 'OP'
AND B.CHARGE_AMOUNT > 0
AND A.SERVICE_AREA_ID = '10000'
GROUP BY A.[STRATA_ENCOUNTER_REC_NBR],
CASE 
WHEN (B.[PRIN_GL_BUILDING_ID] IS NULL OR B.[PRIN_GL_BUILDING_ID] = '1080') AND B.[PATIENT_AGE_DOS] < 18 THEN '1081'
WHEN B.[PRIN_GL_BUILDING_ID] IS NULL THEN C.GL_BUILDING_ID ELSE B.PRIN_GL_BUILDING_ID END
HAVING SUM(A.CHARGE_AMOUNT) > 0)
,
OBS AS
(SELECT B.[STRATA_ENCOUNTER_REC_NBR],
'Observation' POPL,  --4,881
CASE WHEN B.[PRIN_GL_BUILDING_ID] IS NULL THEN C.GL_BUILDING_ID ELSE B.PRIN_GL_BUILDING_ID END AS PRIN_GL_BUILDING_ID
FROM
[Mart_UWHealth].[STRATA_COST_ACCOUNT_HB] B 
LEFT JOIN PRIN_BUILD C  ON B.[STRATA_ENCOUNTER_REC_NBR] = C.[STRATA_ENCOUNTER_REC_NBR]  AND C.RANK1 = 1
WHERE 1=1
AND B.[PATIENT_TYPE_CD] = '3' --	3 - Observation
AND B.DISCHARGE_DT >= '3/1/2024'
AND B.DISCHARGE_DT <= (SELECT END_DT FROM END_DT)
AND B.[INOUT_IND] = 'OP'
AND B.CHARGE_AMOUNT > 0
AND B.SERVICE_AREA_ID = '10000'
GROUP BY B.[STRATA_ENCOUNTER_REC_NBR],
CASE WHEN B.[PRIN_GL_BUILDING_ID] IS NULL THEN C.GL_BUILDING_ID ELSE B.PRIN_GL_BUILDING_ID END)
,
FULL_POPL AS          
(
SELECT STRATA_ENCOUNTER_REC_NBR, POPL, PRIN_GL_BUILDING_ID FROM MED_IP UNION ALL
SELECT STRATA_ENCOUNTER_REC_NBR, POPL, PRIN_GL_BUILDING_ID FROM ED_NO_IP UNION ALL
SELECT STRATA_ENCOUNTER_REC_NBR, POPL, PRIN_GL_BUILDING_ID FROM OBS)

SELECT 
POPL,
[DISCHARGE_STATUS_CD],
[DISCHARGE_STATUS],
LOCATION,
PAYOR_RISK_FLG,
FIN_MODEL_PAYOR_GRP,
DISCHARGE_MONTH,
COUNT(DISTINCT STRATA_ENCOUNTER_REC_NBR) ED_VISITS
FROM
(
SELECT 
A.STRATA_ENCOUNTER_REC_NBR, 
A.POPL,
B.[DISCHARGE_STATUS_CD],
B.[DISCHARGE_STATUS],
CASE 
WHEN A.PRIN_GL_BUILDING_ID = '1080' THEN 'UH' 
WHEN A.PRIN_GL_BUILDING_ID = '1081' THEN 'AFCH'
WHEN A.PRIN_GL_BUILDING_ID = '1060' THEN 'EMH'
ELSE 'UH' END --3 HARs pushed into UH
LOCATION,
B.[PAYOR_RISK_FLG],
B.[FIN_MODEL_PAYOR_GRP],
C.[MID_YEAR_FISCAL_YEAR_NBR] DISCHARGE_FY,
C.[MID_YEAR_FISCAL_MONTH_NBR] DISCHARGE_FP,
C.[CALENDAR_YEAR_NM] DISCHARGE_CY,
C.[CALENDAR_FISCAL_MONTH_NBR] DISCHARGE_CM,
CONCAT([MONTH_NM_ABBR], ' ',[CALENDAR_YEAR_NM]) DISCHARGE_MONTH,
B.CHARGE_AMOUNT + COALESCE(PB.CHARGE_AMOUNT,0) CHARGE_AMOUNT,
B.ESTIMATED_REIMBURSEMENT + COALESCE(PB.ESTIMATED_REIMBURSEMENT,0) ESTIMATED_REIMBURSEMENT,
CASE WHEN B.PAYOR_RISK_FLG = 'Volume Based' THEN B.ESTIMATED_REIMBURSEMENT + COALESCE(PB.ESTIMATED_REIMBURSEMENT,0) ELSE 0 END VOLUME_BASED_REIMB,
B.DIRECT_COST + COALESCE(PB.DIRECT_COST,0) DIRECT_COST,
B.VAR_INDIRECT_COST + COALESCE(PB.VAR_INDIRECT_COST,0) VAR_INDIRECT_COST,
B.FIXED_INDIRECT_COST + COALESCE(PB.FIXED_INDIRECT_COST,0) FIXED_INDIRECT_COST

FROM FULL_POPL A
INNER JOIN [Mart_UWHealth].[STRATA_COST_ACCOUNT_HB] B ON A.STRATA_ENCOUNTER_REC_NBR = B.STRATA_ENCOUNTER_REC_NBR
INNER JOIN [Modeled_UWHealth].[DIM_DATE] C ON B.DISCHARGE_DT = C.ACTUAL_DT
LEFT JOIN --Subquery of PB Grouped by Matched HB
(SELECT 
A.MATCHED_HB_STRATA_ENCOUNTER,
SUM(A.CHARGE_AMOUNT) CHARGE_AMOUNT,
SUM(A.ESTIMATED_REIMBURSEMENT) ESTIMATED_REIMBURSEMENT,
SUM(A.VAR_DIRECT_COST) VAR_DIRECT_COST,
SUM(A.FIXED_DIRECT_COST) FIXED_DIRECT_COST,
SUM(A.DIRECT_COST) DIRECT_COST,
SUM(A.VAR_INDIRECT_COST) VAR_INDIRECT_COST,
SUM(A.FIXED_INDIRECT_COST) FIXED_INDIRECT_COST
FROM [Mart_UWHealth].[STRATA_COST_ACCOUNT_PB] A
GROUP BY A.MATCHED_HB_STRATA_ENCOUNTER) PB ON A.STRATA_ENCOUNTER_REC_NBR = PB.MATCHED_HB_STRATA_ENCOUNTER) Z
WHERE Z.POPL = 'ED Not Admitted'
GROUP BY POPL,
[DISCHARGE_STATUS_CD],
[DISCHARGE_STATUS],
LOCATION,
PAYOR_RISK_FLG,
FIN_MODEL_PAYOR_GRP,
DISCHARGE_MONTH